# Generated by Django 4.2.7 on 2023-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.CharField(default='', max_length=200),
        ),
    ]
