# Generated by Django 4.2.7 on 2023-11-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
